T262249 add confirm dialog before exit the app in search page
wikimedia/wikipedia-kaios pull request #283
Opened 2020-11-17 18:11 UTC by hueitan

Phabricator Link: https://phabricator.wikimedia.org/T262249

### Problem Statement

When a user uses the back key repeatedly, the app quits, but this behaviour is unexpected.

### Solution

Use Confirm Dialog component before quit

### Note

2020-11-20 16:52 UTC, medied reviewed
Code looks good, I left a comment in the Phabricator thread regarding a small language feedback though: https://phabricator.wikimedia.org/T262249#6637184

2020-11-24 14:48 UTC, stephanebisson requested changes
Looks good.

I found an issue. I don't know if it's a deal breaker but I would like you to look into it.

If you hit back many times quickly the app becomes confused. The RSK changes from "Exit" to "Settings" but the popup stays open.

2020-11-30 10:39 UTC, hueitan commented
> If you hit back many times quickly the app becomes confused. The RSK changes from "Exit" to "Settings" but the popup stays open.

Another step to reproduce on the desktop browser, on the search screen, hold the `backspace` button for few seconds, then the softkey is mess up.

2020-11-30 12:45 UTC, hueitan commented
> I found an issue. I don't know if it's a deal breaker but I would like you to look into it.

This is fixed now, great you notice this behaviour!

2020-11-30 18:21 UTC, stephanebisson approved these changes

2020-11-30 18:21 UTC, merged

2020-12-01 13:16 UTC, hueitan commented on src/components/ConfirmDialog.js
> -    close()
this has side-effect, it should only close one level from the dialog! will look close into it!

2020-12-02 10:48 UTC, hueitan commented on src/components/ConfirmDialog.js
> -    close()
so in general the bug comes from the popup `close` and `show` function, the state doesn't fully update yet but the show/close event is called, so the softkey popup state is mess up with it. the fixed should be considered in https://phabricator.wikimedia.org/T269158